version: '2'
services:

  server:
      image: ${REPOSITORY_SERVER}:${TAG_DEPLOY}
      ports:
        - 8056:8056

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER : root
      MYSQL_DATABASE: dbproject
    ports:
      - 3359:3306
